currencies:
  'bronze': "id:skull:3 name:&6⛁_Moneda_de_bronz lore:&8»&f_x64_⟹_x1_&7⛁_Moneda_de_argint urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDJlZWM1YzVkNTAzMDJmZjEwZDBiZGI2MmQ3OWU2N2EwYWIxMTAxNjk2YWUyN2VmOWQ4MmIzNzk0M2MyYTY1YyJ9fX0="
  'silver': "id:skull:3 name:&7⛁_Moneda_de_argint lore:&8»&f_x10_⟹_x1_&e⛁_Moneda_de_aur urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTM0YjI3YmZjYzhmOWI5NjQ1OTRiNjE4YjExNDZhZjY5ZGUyNzhjZTVlMmUzMDEyY2I0NzFhOWEzY2YzODcxIn19fQ="
  'gold': "id:skull:3 name:&e⛁_Moneda_de_aur lore:&8»&f_x10_⟹_x1_&e&lSac_cu_aur urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBhN2I5NGM0ZTU4MWI2OTkxNTlkNDg4NDZlYzA5MTM5MjUwNjIzN2M4OWE5N2M5MzI0OGEwZDhhYmM5MTZkNSJ9fX0="
  'gold_bag': "id:skull:3 name:&e&l⛁_Sac_cu_aur lore:&8»&f_x10_⟹_&b??? urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk2Y2UxM2ZmNjE1NWZkZjMyMzVkOGQyMjE3NGM1ZGU0YmY1NTEyZjFhZGVkYTFhZmEzZmMyODE4MGYzZjcifX19"
  'crystal': "id:skull:3 name:&b✵_Cristal_✵ lore:&8»&f_Cea_mai_superioara_valuta urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2E1YTA3MTVjNjIxMjJkZWQ2NWFmNGVhZTA5NjlmMjNmNTcxYjBhZmE1MGNmOTNmYzllZTJhZjRjN2IzNGUxMiJ9fX0="

# These values will be used for giving change at the shop and other conversion-related tasks with the currency
currency-worths:
  'silver': "64 bronze"
  'gold': "10 silver"
  'gold_bag': "10 gold"
  'crystal': "10 gold_bag"

top-options:
  # If the player doesn't specify what currency to display the
  # top for, it will default to this value
  default-currency: "gold"

  # The amount of entries to load per page
  per-page: 10

  currency-lang:
    bronze: "bronz"
    silver: "argint"
    gold: "aur"
    gold_bag: "sac cu aur"
    crystal: "cristal"

  list-header:
    - ""
    - "&8&m-+-------&7 &6Top monede &8(&7 $currency$ &8) &m--------+-"
    - ""
  list-footer:
    - ""
    - "&8&m-+----------&7 [ Pagina $page$ ] &8&m-----------+-"

  # Do you want to make certain entries look different?
  # You can do that here. You can also use PlaceholderAPI in these formats
  individual-entry-formats:
    '1': "  &8✪  &f#1  $player$  $value$ $currency$"
    '2': "  &8✪  &f#2  $player$  $value$ $currency$"
    '3': "  &8✪  &f#3  $player$  $value$ $currency$"
  empty-entry-format:
    - "  &8»  &m-------------------------------"
  entry-format:
    - "  &8»  &7#$number$  $player$  $value$ $currency$"

shop-options:
  rows: 3
  price-format: "&7x$amount$ $currency$"
  price-lore:
    - ""
    - "&fPret:"
    - "&8» $prices$"

  # The amount of time in seconds in which the player has to specify an amount for the chosen item
  # before the choice is automatically cancelled if no amount is provided
  choice-timer: 10

  # Pagination settings for the shop
  skipping-points: [0, 8, 9, 17, 18, 26, 27]
  items-per-page: 21
  next-page-icon: "id:stained_glass_pane:5 name:&aPagina_urmatoare"
  next-button-slots: [8, 17, 26]
  previous-page-icon: "id:stained_glass_pane:1 name:&aPagina_anterioara"
  previous-button-slots: [0, 9, 18]

bank-options:
  title: "Banca » Depoziteaza aici"
  rows: 6
  items:
    '#': "id:stained_glass_pane:7 name:_"

    # Don't change this symbol
    'd': "id:emerald name:&aDepoziteaza lore:&7Click_aici_pentru_a_depozita|&7monedele_introduse_in_banca!"
  layout:
    - "- - - - - - - - -"
    - "- - - - - - - - -"
    - "- - - - - - - - -"
    - "# # # # # # # # #"
    - "# # # # d # # # #"
    - "# # # # # # # # #"

wallet-options:
  item: "id:skull:3 name:&dPortofel lore:&7Acest_item_iti_poate_depozita_monedele|&7si_le_poate_tine_in_siguranta_de_orice|&7jucator_care_si-a_propus_sa_te_omoare.|&7Fiecare_portofel_are_un_inventar_propriu|&7|&f&nInventar|&8»_&6$bronze$_bronz|&8»_&7$silver$_argint|&8»_&e$gold$_aur|&8»_&e&l$goldbag$_sac_cu_aur|&8»_&b$crystal$_cristal urlCode:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk1YjhkYWU5NmUzOWE3YjQ3NDU2OTdlZmIxZGU2ODFlNWZkOTRkNzUwYWIwOWNiOWYyM2ZmN2U3MmEyYTMzZSJ9fX0="
  item-name: "Portofel"
  title: " Portofel"
  rows: 1
  # (in seconds)
  cooldown: 2

bank-inventory-options:
  title: "Banca » Inventar"
  rows: 6
  skipping-points: [0, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 53]

  items-per-page: 42

  next-page-icon: "id:stained_glass_pane:5 name:&aPagina_urmatoare lore:&7Pagina_curenta:_$page$"
  next-button-slots: [8, 17, 26, 35, 44, 53]

  previous-page-icon: "id:stained_glass_pane:1 name:&aPagina_anterioara lore:&7Pagina_curenta:_$page$"
  previous-button-slots: [0, 9, 18, 27, 36, 45]

repair-costs:
  # For all items that have durability
  durability:
    durability-given: 100
    costs:
      - "1 silver"

  # Only works if you have AtomGadgets
  # These are the costs for replenishing uses of gadgets
  gadgets:
  # The ID of the targeted gadget
    'grappling-hook':
      uses-given: 10
      costs:
        - "1 silver"
    'blowpipe':
      uses-given: 3
      costs:
        - "1 silver"

sounds:
  # Will play when an item was bought on shop or when money was stored
  successful-action: "VILLAGER_YES 5 1"
  # Will play when players turn a page in their bank GUIs or shop menus
  page-turn: "CLICK 5 2"
  # Will play when players are required to specify the amount of items they want to buy
  require-input: "VILLAGER_HAGGLE 5 1"
  # Will play when players cancel specifying the amount
  cancel-input: "VILLAGER_NO 5 1"
  wallet-open: "HORSE_SADDLE 5 2"